### ISSUE TITLE
Example or Method to add Notes (specifically internalNotes)

### ISSUE THREAD

**Issue by t3chguy** [JustMaier/node-shipstation#1]
I tried manually leveraging the .put method to modify the Order Resource to add an internalNote, but it did not work for me - could you please suggest a snippet I could use to do this using your module?

Thanks in Advance.

**Comment by JustMaier** [comment]
Which endpoint are you trying to use? I didn't see any like that in their [API docs](https://www.shipstation.com/developer-api/)...

**Comment by t3chguy** [comment]
Now I've noticed that the createOrder method can be used to edit orders, but it looks like to edit an order I have to pass it the whole old order object, I can't just pass back a single value for it to be modified, do you know any more about modifying orders?

**Comment by JustMaier** [comment]
Hey @t3chguy, I just added a new helper method to update an order:

``` javascript
updateOrder(123123123, {internalNotes:'Something'}, function(err, res, body){
    //body is the updated order
}
```

**Comment by t3chguy** [comment]
Any chance you could push that over to NPM too?

Thanks

**Comment by JustMaier** [comment]
It's live on NPM as well.
