### ISSUE TITLE
Please publish the 0.1.3 to npm

### ISSUE THREAD

**Issue by chaddjohnson** [JustMaier/node-shipstation#7]
Thank you for the library.

Super frustrating thing happened.

I thought I was using the rate limiting functionality that's in the latest version, but turns out v0.1.1 which is on npm doesn't have the rate limiting functionality included. So, this whole time I was wondering why I was getting "Too many requests" from ShipStation.

Would you mind publishing the latest version to npm? It would really help a lot.

**Comment by JustMaier** [comment]
Hey @chaddjohnson sorry about that. v0.1.3 has been published to NPM.

**Comment by chaddjohnson** [comment]
@JustMaier Thank you sir!
